import tkinter as _

_.ROUND = _.BUTT

PIXELS_PER_INCH = 96
TILE_UNIT_32 = PIXELS_PER_INCH / 32  # 3
TILE_UNIT_16 = PIXELS_PER_INCH / 16  # 6
TILE_UNIT = TILE_UNIT_16
CANVAS_TILE_UNIT_LENGTH = 64
CANVAS_PIXEL_LENGTH = CANVAS_TILE_UNIT_LENGTH * TILE_UNIT  # 384

FULL_CANVAS = CANVAS_PIXEL_LENGTH - TILE_UNIT
TWO_THIRDS_CANVAS = (CANVAS_PIXEL_LENGTH / 3) * 2 - TILE_UNIT
HALF_CANVAS = CANVAS_PIXEL_LENGTH / 2 - TILE_UNIT
THIRD_CANVAS = CANVAS_PIXEL_LENGTH / 3 - TILE_UNIT
QUARTER_CANVAS = CANVAS_PIXEL_LENGTH / 4 - TILE_UNIT
EIGHTH_CANVAS = CANVAS_PIXEL_LENGTH / 8 - TILE_UNIT
NINTH_CANVAS = CANVAS_PIXEL_LENGTH / 9 - TILE_UNIT
SIXTEENTH_CANVAS = CANVAS_PIXEL_LENGTH / 16 - TILE_UNIT

TWO_THIRDS_CANVAS_OFFSET = TWO_THIRDS_CANVAS + (TILE_UNIT * 1/3)
HALF_CANVAS_OFFSET = HALF_CANVAS + TILE_UNIT
THIRD_CANVAS_OFFSET = THIRD_CANVAS + (TILE_UNIT * 2/3)
QUARTER_CANVAS_OFFSET = QUARTER_CANVAS + (TILE_UNIT * 3/4)
EIGHTH_CANVAS_OFFSET = EIGHTH_CANVAS + (TILE_UNIT * 7/8)
NINTH_CANVAS_OFFSET = NINTH_CANVAS + (TILE_UNIT * 8/9)
SIXTEENTH_CANVAS_OFFSET = SIXTEENTH_CANVAS + (TILE_UNIT * 15/16)

STANDARD_SIZES = [
    FULL_CANVAS,
    HALF_CANVAS,
    HALF_CANVAS_OFFSET,
    TWO_THIRDS_CANVAS,
    TWO_THIRDS_CANVAS_OFFSET,
    THIRD_CANVAS,
    THIRD_CANVAS_OFFSET,
    QUARTER_CANVAS,
    QUARTER_CANVAS_OFFSET,
    EIGHTH_CANVAS,
    EIGHTH_CANVAS_OFFSET,
    NINTH_CANVAS,
    NINTH_CANVAS_OFFSET,
    SIXTEENTH_CANVAS,
    SIXTEENTH_CANVAS_OFFSET
]

STANDARD_SIZES_NAME_MAP = {
    FULL_CANVAS: "full",
    TWO_THIRDS_CANVAS: "two_third",
    TWO_THIRDS_CANVAS_OFFSET: "two_third_offset",
    HALF_CANVAS: "half",
    HALF_CANVAS_OFFSET: "half_offset",
    THIRD_CANVAS: "third",
    THIRD_CANVAS_OFFSET: "third_offset",
    QUARTER_CANVAS: "quarter",
    QUARTER_CANVAS_OFFSET: "quarter_offset",
    EIGHTH_CANVAS: "eighth",
    EIGHTH_CANVAS_OFFSET: "eighth_offset",
    NINTH_CANVAS: "ninth",
    NINTH_CANVAS_OFFSET: "ninth_offset",
    SIXTEENTH_CANVAS: "sixteenth",
    SIXTEENTH_CANVAS_OFFSET: "sixteenth_offset"
}
